# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Вторая практика\Derevo\ui\audio.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(578, 434)
        MainWindow.setStyleSheet("#MainWindow{\n"
"background-color: qconicalgradient(cx:0.505773, cy:0.517, angle:317.8, stop:0.0852273 rgba(65, 103, 169, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet("#pushButton {\n"
"font: 20pt \"Matura MT Script Capitals\";\n"
"color: #000000;\n"
"background: #3a09e8;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton:hover {\n"
"font: 20pt \"Matura MT Script Capitals\";\n"
"background: #2d7391;\n"
"color: #000000;\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setStyleSheet("#pushButton_3 {\n"
"font: 20pt \"Matura MT Script Capitals\";\n"
"color: #000000;\n"
"background: #3a09e8;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_3:hover {\n"
"font: 20pt \"Matura MT Script Capitals\";\n"
"background: #2d7391;\n"
"color: #000000;\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 4, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("#label_2{\n"
"font: 38pt \"Matura MT Script Capitals\";\n"
"color: #000000;\n"
"background:#3a09e8;\n"
"border-radius: 10px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 3)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setStyleSheet("#pushButton_4{\n"
"font: 20pt \"Matura MT Script Capitals\";\n"
"color: #000000;\n"
"background: #3a09e8;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_4:hover {\n"
"font: 20pt \"Matura MT Script Capitals\";\n"
"background: #2d7391;\n"
"color: #000000;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 5, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setStyleSheet("#pushButton_5 {\n"
"font: 20pt \"Matura MT Script Capitals\";\n"
"color: #000000;\n"
"background: #3a09e8;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_5:hover {\n"
"font: 20pt \"Matura MT Script Capitals\";\n"
"background: #2d7391;\n"
"color: #000000;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 5, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setStyleSheet("#pushButton_6{\n"
"font: 20pt \"Matura MT Script Capitals\";\n"
"color: #000000;\n"
"background: #3a09e8;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_6:hover {\n"
"font: 20pt \"Matura MT Script Capitals\";\n"
"background: #2d7391;\n"
"color: #000000;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 5, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"font: 20pt \"Matura MT Script Capitals\";\n"
"color: #000000;\n"
"background: #3a09e8;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_2:hover {\n"
"font: 20pt \"Matura MT Script Capitals\";\n"
"background: #2d7391;\n"
"color: #000000;\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 4, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setStyleSheet("#comboBox{\n"
"font: 9pt \"Matura MT Script Capitals\";\n"
"color: rgb(0, 0, 127);\n"
"background-color:#3a09e8\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setStyleSheet("QHeaderView {\n"
"background-color: #3a09e8;\n"
"font-size:13px;\n"
"}\n"
"QHeaderView::section:horizontal {\n"
"color: #fff;\n"
"border-style: solid;\n"
"border-radius: 4px;\n"
"background-color: qlineargradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0 #4287ff, stop: 1 #356ccc);\n"
"}\n"
"QTableView {\n"
"border: 2px solid #3a09e8;\n"
"border-top-color: #4287ff;\n"
"border-radius: 10px;\n"
"background-color: #EEFFFF;\n"
"gridline-color: #777;\n"
"selection-background-color: #ccdfff;\n"
"color:#000000;\n"
"font-size:14px;\n"
"font-weight: bold;\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 4, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("#label {\n"
"border-radius:20px;\n"
"background-color:#3a09e8\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 2, 3)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setStyleSheet("#pushButton_7{\n"
"font: 20pt \"Matura MT Script Capitals\";\n"
"color: #000000;\n"
"background: #3a09e8;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_7:hover {\n"
"font: 20pt \"Matura MT Script Capitals\";\n"
"background: #2d7391;\n"
"color: #000000;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 3, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setStyleSheet("#pushButton_8{\n"
"font: 20pt \"Matura MT Script Capitals\";\n"
"color: #000000;\n"
"background: #3a09e8;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#pushButton_8:hover {\n"
"font: 20pt \"Matura MT Script Capitals\";\n"
"background: #2d7391;\n"
"color: #000000;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 3, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionADA = QtWidgets.QAction(MainWindow)
        self.actionADA.setShortcutVisibleInContextMenu(False)
        self.actionADA.setObjectName("actionADA")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Left"))
        self.pushButton_3.setText(_translate("MainWindow", "Right"))
        self.label_2.setText(_translate("MainWindow", "MediaPlayer"))
        self.pushButton_4.setText(_translate("MainWindow", "Add album"))
        self.pushButton_5.setText(_translate("MainWindow", "Delete track"))
        self.pushButton_6.setText(_translate("MainWindow", "Add track"))
        self.pushButton_2.setText(_translate("MainWindow", "Payse"))
        self.pushButton_7.setText(_translate("MainWindow", "Delete album"))
        self.pushButton_8.setText(_translate("MainWindow", "Info"))
        self.actionADA.setText(_translate("MainWindow", "ADA"))
